### ISSUE TITLE
Update Project 3 Overview and things to do (after discussion with Chris)

### ISSUE THREAD

**Issue by harryh1993** [berkeley-stat222/mousestyles#105]
After discussion with Chris this Monday, we need to settle down our tasks in details so that we could begin the parameter estimation and model building. Here are the things that are on my mind:

- [x] Determine the stages for the Markov Chain. We need to decide whether to contain the AS as a state in our model or should we only contain other visible states and label them as AS
- [x] Estimate the generator matrix of the MC model. Might use MLE or other approach. This step is done with assumption of constant rate / time homogeneity
- [x] Find an approach to iteratively update the previous estimation based on the time information and create a changing rate / time non-homogeneous MC model for the AS Dynamics and better model the behaviors, such as (FFF...DDD)
- [x] Consult with possibly Adhikari or other professors to see if the model and estimation makes sense
- [ ] Once the model was established, use it to:
 + [x] generate 'fake' mouse day and compare to real data, might need to use Monte Carlo MC techniques
 + [ ] calculate stationary probability to generalize the stages distribution, check if they agree with overall observations.

@wyshi @lynnzhao92 @mingyungkim @HongfeiZhao @Chenyu-Renee 

Please feel free to add and modify anything.

**Comment by harryh1993** [comment]
- States: F, W, AS_O, IS
- Estimation: 
 - divide into small intervals per mouse per day
 - calculate the matrices
- Simulation:
 - Model Evaluation
 - "Stationary Distribution": proportion of time in each strain of mouse; compare the difference to get an inference of the difference in their behavior

**Comment by jarrodmillman** [comment]
@harryh1993 Is it OK to close this?

**Comment by harryh1993** [comment]
Yes please close it
