### ISSUE TITLE
Add time interpolation to data loader function

### ISSUE THREAD

**Issue by peterasujan** [berkeley-stat222/mousestyles#106]
<t, x, y> table only records a measurement when movement is sufficiently large (>1cm). Evenly-spaced time measurements are needed for several subprojects, so we should fill in missing time values.

**Comment by jarrodmillman** [comment]
@peterasujan Should we close this?

**Comment by dylandaniels** [comment]
Peter and I discussed this and it turned out this wasn't necessary because of different needs for different projects. I'm closing this now.
