### ISSUE TITLE
Data Questions

### ISSUE THREAD

**Issue by dylandaniels** [berkeley-stat222/mousestyles#107]
Hi Chris (@qualiaphile), 

Thanks so much for meeting with us this past Monday! We had a couple questions about the data and wanted to see if we could get access to some additional data:

1) We currently don't have numbers for how much food/water each mouse eat/drank on each day. Would you be able to send us this data so we can incorporate this into our analysis?

2) We're a bit confused by the values in the txy_coords/recordingStartTimeEndTime directory. We understand that the times are expressed in seconds, but (2.a) is there any meaning behind the start (usually ~50000) and stop time values (usually ~130000)? (2.b) When we calculate the total time between the stop and start, sometimes the number of seconds spans a whole day (86400 seconds), but other times much less...what's the reason behind this?

Thanks, Chris!

**Comment by qualiaphile** [comment]
hi all, so let's see if i can help:

1) this can be calculated from the 1921 x 9 Food/Water feature matrix by summing over the 11 time bins for the day.

2) (short answer: no real meaning).  every day there was a "maintenance period" of about (but different for each MD) ~ 2hrs.  the recording start and stop times describe when the system of sensors (F/W,etc) gets turned back on and when it gets shut down, respectively, for that MD.

keep asking away!
-chris

**Comment by dylandaniels** [comment]
Thanks for the response... is there any way to recover time of day, then? @qualiaphile

**Comment by qualiaphile** [comment]
the start time is seconds from midnight.

**Comment by boyinggong** [comment]
The assumption is that, each mouse drink/eat at a constant rate, which means the water/food consumption is proportional to the time they drink/eat. To obtain the water/food consumption in a given interval (during which the drinking/eating happens), we just use `the total consumption/total drinking or eating time * interval length`. Is that right? Thanks.  @qualiaphile

**Comment by qualiaphile** [comment]
to get the total food (or water) you just sum the 11 time bins of food (or water) numbers in a given day.  for Food this gives you grams [g] and for Water this is in milligrams [mg].  to get the food in a given eating interval during a mouse-day (MD) you multiply this total for the day by the fraction of total eating time in the MD occurring in this feeding interval.

**Comment by peterasujan** [comment]
@qualiaphile I noticed that in the `all_features_mousedays_11bins.npy` file, most mice have 12 days of data, numbered 5-16. It looks something like this:
```
      strain  mouse  day hour  ASProbability  ASNumbers  ASDurations
0          0      0    5    0       0.260422          1    31.250667   
1          0      0    6    0       0.118975          1    16.490667   
2          0      0    7    0       0.111603          1    13.392333   
3          0      0    8    0       0.146633          1    17.596000   
4          0      0    9    0       0.058850          1     7.127000   
5          0      0   10    0       0.089600          1    10.752000   
6          0      0   11    0       0.060989          1    13.956000   
7          0      0   12    0       0.000000          0     0.000000   
8          0      0   13    0       0.023039          2    21.027000   
9          0      0   14    0       0.147817          1    17.738000   
10         0      0   15    0       0.123925          1    14.871000   
11         0      0   16    0       0.147053          2    18.255333   
```

However, in the `txy_coords` directory, the numbering is 0-11.
```bash
$ ls CT/CT_strain0_mouse0_day*
CT/CT_strain0_mouse0_day0.npy   CT/CT_strain0_mouse0_day4.npy
CT/CT_strain0_mouse0_day10.npy  CT/CT_strain0_mouse0_day5.npy
CT/CT_strain0_mouse0_day11.npy  CT/CT_strain0_mouse0_day6.npy
CT/CT_strain0_mouse0_day1.npy   CT/CT_strain0_mouse0_day7.npy
CT/CT_strain0_mouse0_day2.npy   CT/CT_strain0_mouse0_day8.npy
CT/CT_strain0_mouse0_day3.npy   CT/CT_strain0_mouse0_day9.npy
```

I just wanted to verify my intuition that days 5-16 in the earlier data correspond to 0-11 in the `txy_coords` directory. Is that correct, or is something else going on?

**Comment by qualiaphile** [comment]
Yes, the numbering 5-16 is actual days in the experiment, whereas 0-11 is them more conveniently relabled. Hope that Helps.

**Comment by jarrodmillman** [comment]
@peterasujan Is this ready to close?
