### ISSUE TITLE
PLANNING: Behavioral model

### ISSUE THREAD

**Issue by peterasujan** [berkeley-stat222/mousestyles#115]
@shamindras @dylandaniels 
Here is my initial spec for the generic function (to be applied after any pre-processing):

```python
def process_raw_intervals(total_consumption, intervals, as_probability, epsilon):
    """
    Takes `total_consumption` and the data in `intervals` and
    decomposes it into a tree of behavioral summary statistics.
    """
```
Feel free to add more below, or edit this top post.

**Comment by dylandaniels** [comment]
```
def total_time(strain, mouse, day):
    """Returns the total amount of time recorded for a certain mouse-day.
    """

def active_time(strain, mouse, day):
    """Returns the total amount of active time recorded for a certain mouse-day.
    """

def total_amount(strain, mouse, day, feature):
    """Returns the total amount consumed/moved for one of the following features: 
     food ("F"), water ("W"), and locomotion ("L").
    """
```

**Comment by dylandaniels** [comment]
Something we need to do is add a data loader for getting the start time and end time for each day. I'll create a function for that today.

**Comment by shamindras** [comment]
```python
def total_bouts_count(strain, mouse, day, bout_threshold):
    """Returns the total number (i.e. count) of all bouts recorded within a given threshold on a certain mouse-day.
    """

def total_events_count(strain, mouse, day):
    """Returns the total time of all bouts recorded for a certain mouse-day.
    """

def total_events_count(strain, mouse, day):
    """Returns the total time of all bouts recorded for a certain mouse-day.
    """
```

**Comment by peterasujan** [comment]
@dylandaniels @shamindras I pushed an initial attempt to dylan's fork if you guys wouldn't mind taking a look.

**Comment by peterasujan** [comment]
@jarrodmillman weird place to put this question, but what are your thoughts on relative imports (e.g. https://github.com/scikit-learn/scikit-learn/blob/master/sklearn/svm/classes.py#L8) vs. absolute, like `from mousestyles import data`.

**Comment by shamindras** [comment]
List of stuff TODO:

- [ ] fix data sort() warning in the `data loader` functions 
- [ ] Piazza announcement for Day `5 --> 0` change
- [ ] Add units for output
- [ ] Ask Jarrod to MRG
- [ ] Finish report
