### ISSUE TITLE
TASK LIST: Project 4 Ultradian analysis

### ISSUE THREAD

**Issue by boyinggong** [berkeley-stat222/mousestyles#116]
- Aggregate the interval data based on n-minute time intervals, return a time series. (standardize to per hour data)
```
def aggegate_interval(strain, mouse, feature, bin_width):
    """
    data loaded from data.load_intervals(feature)

    Parameters
    ---------------
    feature: {"AS", "Food", "IS", "M_AS", "M_IS", "Water", "Distance", "AS_Intensity", "AS_prob"}
    bin_width: number of minutes of time interval for data aggregation

    Returns
    ----------
    ts: pandas.tseries
        a pandas time series of length 12(day)*24(hour)*60(minute)/n
    """
```
- Period detectiom: Lomb-Scargle Algorithm
    - Reference
[Comparison of Lomb-Scargle implementation in Python](https://jakevdp.github.io/blog/2015/06/13/lomb-scargle-in-python/)
[Generalized vs Standard Lomb-Scargle in astroML package](http://www.astroml.org/paper_figures/CIDU2012/fig_LS_sg_comparison.html) (with example of significance level calculation) [Another link]
(http://www.astroml.org/book_figures/chapter10/fig_LS_sg_comparison.html)
[Example of Lomb-Scargle Algorithm in astroML package](http://www.astroml.org/book_figures/chapter10/fig_LS_example.html) (with example of significance level calculation) [Another link](http://www.astroml.org/book_figures/chapter10/fig_LS_example.html#book-fig-chapter10-fig-ls-example)
[Lomb-Scargle in scipy package](http://docs.scipy.org/doc/scipy-0.16.0/reference/generated/scipy.signal.lombscargle.html)

    - functions: 
```
def plot_lomb_scargle(stain, mouse, day, feature, bin_width):
    """
    we detect ultradian period from 2 hours to 48 hours (to be decided)

    Returns
    ----------
    Periodograms: plot
        Lomb-Scargle Periodograms with horizontal line indicating 
        significance level = 0.05, 0.01, 0.001, etc.
    significant period: numpy.array
        period in number of bin width
    """
```

- Seasonal decomposition
    - Observed = Trend + Seasonal + Residuals
    - fit time series model using residuals from the seasonal decomposition and detect the autocorrelation relationship
    - Using residuals to calculate the SD/CI. 
    - Prediction of future features (F/W consumption) using Trend + Seasonal trem
    - Reference 
    [Seasonal decomposition in statsmodels package](http://statsmodels.sourceforge.net/0.6.0/release/version0.6.html), 
[An implementation using statsmodel package](https://gist.github.com/balzer82/5cec6ad7adc1b550e7ee)

- Mixed-effects model
    - Reference: [stats model implementation](http://statsmodels.sourceforge.net/stable/examples/notebooks/generated/mixed_lm_example.html)

**Comment by boyinggong** [comment]
@jarrodmillman @peterasujan @dylandaniels @shamindras We want to create a branch named `ultradian` under berkeley-stat222/mousestyles, we don't think we have access to do that. Could you please do that for us? Then we may push our changes on that branch.

**Comment by shamindras** [comment]
@boyinggong - I'm not quite sure what you mean by not having >access to do that?

Generally the branch is created locally and pushed to your fork and then a pull request is submitted. And the branch is then created for you to make relevant changes based on code review. Sorry if I am misunderstanding your request.

I am on `gitter` at the moment if you want to clarify anything 😄
