### ISSUE TITLE
Overview of Overview

### ISSUE THREAD

**Issue by HongfeiZhao** [berkeley-stat222/mousestyles#12]
- [x] Read Overview
- [x] Come up summaries

**Comment by jarrodmillman** [comment]
For Monday, your task is to produce a 1 page summary here:
https://github.com/berkeley-stat222/mousestyles/blob/master/doc/problem/overview.md

Your goal is to understand the problem.  You are welcome to look at the code, but you shouldn't be working with code at this point.  You also probably don't want to focus on the algorithms yet either.

If this isn't clear, please reread the project assignment:
https://github.com/berkeley-stat222/mousestyles/blob/master/doc/assignment/mouse.pdf

Feel free to discuss the issue on Piazza.

**Comment by peterasujan** [comment]
Some notes from class discussion (not super comprehensive):
- discuss reasons for **computational** ethology
- Mention home cage monitoring
- Glossary?
- Why is this relevant to statisticians? (populations, sampling, where does the _randomness_ come from?)

**Comment by jcyhong** [comment]
In addition to the suggestions by Peter, the overview should include a more detailed description of the dataset. How many variables? What are the variables? What do the variables stand for? How frequent are the readings? How many strains? How many mice are involved? Date and location of the experiments? etc.

**Comment by boyinggong** [comment]
Suggestions from class discussion: add data description section.
