### ISSUE TITLE
clean-up plot example

### ISSUE THREAD

**Issue by jarrodmillman** [berkeley-stat222/mousestyles#133]
Feel free to assign this to anyone in your team, I just assigned it to @alannaiverson to make sure someone was initially responsible.

This file needs to be cleaned up:
https://github.com/berkeley-stat222/mousestyles/blob/master/doc/source/report/plots/heat_map_0_0_0.py

I would imagine something like this (with my comments removed would be what you want):

```
import numpy as np
import matplotlib.pyplot as plt

# clean up imports
from mousestyles.data import load_movement
from mousestyles.viz import cage_heat_map

# you may need more code than this, but the idea is that you put as much code in the
# plot function as possible, so you can easily make as many of these plots as you
# wish.
d = load_movement(0, 0, 0)
cage_heat_map(d)
```

You will need to made actually implement `mousestyles.viz.cage_heat_map` with docstrings and tests.  I just made up the name, so you will want to think if it is reasonable or if you can come up with something better.

**Comment by alannaiverson** [comment]
I thought simply having the script (that now uses the data loader functions) was sufficient, rather than creating a function to produce a single plot? What am I missing? I edited the initial script on my branch to use the data loader functions correctly, too.
