### ISSUE TITLE
GITFLOW: Create CONTRIBUTOR.md and include: (doc/develop/..)

### ISSUE THREAD

**Issue by peterasujan** [berkeley-stat222/mousestyles#14]
- [x] how to make pull request
- [x] how to make issues, report bugs
- [ ] dependencies (should specify in setup.py / requirements.txt)
- [x] set up multiple remotes (i.e. upstream and origin)
- [x] pull new updates
- [x] checkout to a feature branch
- [x] stage and commit files

**Comment by shamindras** [comment]
I just added in @peterasujan's additional requests in the checklist above from #15.

I believe #15 can be closed now

**Comment by shamindras** [comment]
Also from #15 @dylandaniels linked to this great [gitflow](https://www.atlassian.com/git/tutorials/comparing-workflows/forking-workflow) resource from Atlassian

**Comment by shamindras** [comment]
@peterasujan mentioned in gitter to include the following code:
https://github.com/thoughtbot/guides/tree/master/code-review

in CONTRIBUTING.rst. @jJasonWang - could you please add this link into CONTRIBUTING.rst and send a pull request to @aksam-ahmad ?

**Comment by jJasonWang** [comment]
@shamindras, yeah. We probably should have a discussion and make sure everything suggested by people add to the CONTRIBUTING.rst. For example, the naming convention for feature branch and rebase with -i.

**Comment by shamindras** [comment]
@jJasonWang - a few more things from the discussion today to add in this file:

- [ ] Change issue 15 back to 14 in the file
- [ ] add `git rebase -i` option as mentioned by @peterasujan 
- [ ] change naming convention as mentioned by @dylandaniels to remove `your-Github-username` requirement and replace with a more useful branch name based on feature e.g. `performance-speedups`

**Comment by jJasonWang** [comment]
I added a documentation for SSH key (see PR #52). We will discuss and update the CONTRIBUTING.rst tomorrow!

**Comment by jJasonWang** [comment]
@peterasujan, do you have any good resources for `git rebase -i`. I saw the man page of it and some online resources, but I am still not sure what it's about. Thanks!

**Comment by peterasujan** [comment]
@jJasonWang here are a couple:
https://help.github.com/articles/using-git-rebase/
https://robots.thoughtbot.com/git-interactive-rebase-squash-amend-rewriting-history

**Comment by shamindras** [comment]
@peterasujan - would you mind adding in a section on git hooks to CONTRIBUTING.rst and the `rebase -i` methods which you like to use?

I can review and MRG as required.

**Comment by peterasujan** [comment]
@shamindras Yep, working on this now.

**Comment by peterasujan** [comment]
@shamindras I completed those in #70. There is one checkmark left at the top - is this still something we want to address?
