### ISSUE TITLE
Understand and create a recipe of pull request work flow

### ISSUE THREAD

**Issue by peterasujan** [berkeley-stat222/mousestyles#15]
It would be nice to include general git workflow advice here too. This could include a brief overview of how to:
- set up multiple remotes (i.e. upstream and origin)
- pull new updates
- checkout to a feature branch
- stage and commit files

I have a section I'd like to add on how to set up a pre-commit hook for running tests and style checks.

**Comment by dylandaniels** [comment]
Here's a good article on this I just read to refresh my knowledge:

https://www.atlassian.com/git/tutorials/comparing-workflows/forking-workflow

**Comment by shamindras** [comment]
great points @dylandaniels and @peterasujan :+1: 

This is being covered in #14 in the CONTRIBUTING.rst documentation. As such Could we please close this issue and add any comments in #14?

**Comment by shamindras** [comment]
This is now combined into #14
