### ISSUE TITLE
plot distances for report

### ISSUE THREAD

**Issue by jarrodmillman** [berkeley-stat222/mousestyles#164]
@doutib I  merged pull request #119 .  I tried to build the report and noticed that you hadn't included your plot in it.  Then when I started to add the plots to the report (see #163 ), I noticed that the plotting code takes too long to run.  Could save the data you want to plot?  Then you could just load and plot it.  Just make sure to include the code you use to generate the data.

When you add the data you want to plot, please clean up the plotting script.  For example, for the lines

```
plt.style.use('ggplot')
plt.style.use('seaborn-notebook')
```

won't the first one be executed and then undone when the second one is executed?

**Comment by doutib** [comment]
Yes I will do this, you are right it is a bit slow. For the plots the two styles can be used together, I think this is more aesthetic in this case.

**Comment by doutib** [comment]
@jarrodmillman should I save the plot instead?
If not, how should I save the data: can I use numpy.save in a python script somewhere?

**Comment by doutib** [comment]
@jarrodmillman Thanks for merging!
We can close this issue now.
