### ISSUE TITLE
Task List: Final revision of project reports  

### ISSUE THREAD

**Issue by jcpalumbo3** [berkeley-stat222/mousestyles#165]
Alanna, Sici, and I will do a final edit of the project reports towards the middle of this coming week. Before we begin editing a project, we will give that group a heads up in case they have any final touches they'd like to add. 

- [ ] Overview of the Project
- [ ] Project 1: Behavior
- [ ] Project 2: Path
- [ ] Project 3: Dynamics
- [ ] Project 4: Ultradian
- [ ] Project 5: Classification
- [ ] Project 6: Distribution
- [ ] Check final generated HTML reports

@sicihuang @alannaiverson

**Comment by jarrodmillman** [comment]
@jcpalumbo3 Should we close this?
