### ISSUE TITLE
DOCFLOW: Create the Checklist Documentation to tell what code should have

### ISSUE THREAD

**Issue by peterasujan** [berkeley-stat222/mousestyles#17]
- [x] Tests (this is a separate document... TESTFLOW.md) #28 
- [x] Docstrings
- [x] Style Guides (package pep8 automatically check style errors), verb named function, Python2/3 Compatibility, Auto Check Doc. Standard are followed @sicihuang @jcpalumbo3

**Comment by peterasujan** [comment]
If we want to use the pep8 package for style checking, there's a kind of "super package" called [flake8](https://pypi.python.org/pypi/flake8) that runs both pep8 and pyflakes (a linter).

**Comment by dylandaniels** [comment]
The docstring section is really lacking. I couldn't really use it for writing a function today. It should tell me what the standard is, not why I'd want to use docstrings.

See: https://github.com/numpy/numpy/blob/master/doc/HOWTO_DOCUMENT.rst.txt#docstring-standard

**Comment by jcpalumbo3** [comment]
Added Alanna's doctesting section and fixed a couple mistakes in the documentation that Peter noticed. It'll need another round of revisions which will address Dylan's suggestions by either our group or our rightful successors, the glorious next-in-liners to the docflow legacy.
