### ISSUE TITLE
Project 2: Function to visualize paths in the original form

### ISSUE THREAD

**Issue by togawa28** [berkeley-stat222/mousestyles#170]
Besides the plots for key features of paths (see the pull request #162) we need a function to plot paths in their original form, which would look like: 
![example_plot_several_paths](https://cloud.githubusercontent.com/assets/14063064/15121086/a0dcfdd2-15cd-11e6-8b75-41a0e4ac0677.png)

This issue was originally suggested in #122 but is separated since we should discuss a bit more about additional functionalities, such as
1. adding some rectangle to illustrate the area for home, water, and food (by @jJasonWang)
2. showing some key features at the same time (e.g. speed) by changing the color of the path (by @aksam-ahmad)
3. controlling some plot parameters like color, types of plots (e.g. points or a line), the size of points, the width of line, etc. 

@aksam-ahmad, @alannaiverson, @jcpalumbo3, @jJasonWang, @sicihuang, any comments are welcomed!

**Comment by jJasonWang** [comment]
Have you tried to color the path based on the speed? I think it would be hard to find the pattern by it. While we can change the width of the line, I am not sure how its effect will be.

For my idea, I found that it would be hard to set the exact area for home, water, and food.

**Comment by togawa28** [comment]
Your 2 points are fair enough @jJasonWang: I haven't tried using gradient, and the purpose of such functionality might be a bit unclear.

Right now we can modify the width of the line by controling `alpha`. So do you think we are ready to merge?

**Comment by jJasonWang** [comment]
I think the `alpha` control the transparency of the line, right? We can add an argument for `linewidth`. Then it should be ready to merge.

**Comment by togawa28** [comment]
Good point. I just modified. 
Just clarification, we don't have to test the input of this function, do we?

**Comment by jJasonWang** [comment]
We don't have to test the input of the plot function. See the reason in #143.

**Comment by togawa28** [comment]
Thanks @jJasonWang! I missed this pull request but it makes sense now.

**Comment by togawa28** [comment]
I close this issue since the pull request #172 was merged.
