### ISSUE TITLE
CI-FLOW: Travis CI / Coverage, setup.py (Week 2)

### ISSUE THREAD

**Issue by peterasujan** [berkeley-stat222/mousestyles#19]
- [ ] set the license, description, etc. variables in setup.py **moved to #56**
-  [x] CI / Coverage: quick fix, talk to jarrod @jarrodmillman 
    - http://docs.astropy.org/en/stable/development/testguide.html
    - http://pytest.org/latest/goodpractices.html#goodpractices
    - "goodpractices" says "avoid `__init__.py` files in your test directories.", but astropy is doing just that
    - "goodpractices" continues "With inlined tests you might put `__init__.py` into test directories and make them installable as part of your application."
    - I think I would just add the `__init__.py` to the tests directories.
    - you may also need to add the `*npy` files using `package_data` see
    - https://github.com/statlab/permute/blob/master/setup.py

**Comment by aksam-ahmad** [comment]
#21 and #22 - Add test and coverage

**Comment by jarrodmillman** [comment]
See #42 and #50 .
