### ISSUE TITLE
Kernel smoothing and relative distribution for the power laws project

### ISSUE THREAD

**Issue by FengshiNiu** [berkeley-stat222/mousestyles#193]
- [x] Write the function for naive kernel density estimation
- [x] Write the function for kernel estimation for nonnegative random variables using truncated normal density
- [x] Add comparison between relative density (referencing best-fit power distribution) and uniform distribution in the report

**Comment by shamindras** [comment]
@FengshiNiu - can this issue be closed now?

**Comment by FengshiNiu** [comment]
Sure. All done! Pull request #199 has been merged
