### ISSUE TITLE
Shamindra broke everything

### ISSUE THREAD

**Issue by peterasujan** [berkeley-stat222/mousestyles#2]
while fixing #1, @shamindras broke things even more.

**Comment by dylandaniels** [comment]
@shamindras :rage: :interrobang:

**Comment by dylandaniels** [comment]
@shamindras. I've updated your tasks :mask:

- [ ] fix the stuff you broke
- [ ] make it better
- [ ] come to my show on Friday
- [ ] buy my lunch

**Comment by dylandaniels** [comment]
@shamindras. I haven't heard back from you about #2. @peterasujan have you heard from @shamindras?

**Comment by dylandaniels** [comment]
@shamindras please ack back ASAP

**Comment by shamindras** [comment]
Thanks @dylandaniels - it's great having more tasks added to my day :)!

I have 'fixed' the 'broken' 'stuff' now.

I bought us lunch and put it on your tab. Thanks

**Comment by shamindras** [comment]
This is now fixed.
