### ISSUE TITLE
CHATFLOW: Set up Gitter (group chat) for mousestyles

### ISSUE THREAD

**Issue by shamindras** [berkeley-stat222/mousestyles#26]
@jarrodmillman - could you please:

- [ ] set up a [gitter](https://gitter.im) chat for our [repo](https://github.com/berkeley-stat222/mousestyles)

This way everyone can communicate in real time. Gitter is fantastic for discussions and productivity from personal experience on past projects :100: .

**Comment by peterasujan** [comment]
One issue I noticed about using gitter - it seems that it only allows up to 25 people in (free tier) private chat rooms. So, we'd have to be willing to keep the chat public.

**Comment by shamindras** [comment]
This is a good point @peterasujan .

But I feel it is not an issue in this case as [mousestyles](https://github.com/berkeley-stat222/mousestyles) is a *public* repo. So future contributors can join the gitter discussion and still have the history.

Everyone will make sure the discussion is appropriate for the forum and we can flag this on Wednesday.

What do you think?

**Comment by jarrodmillman** [comment]
I tend to prefer to keep everything public.  And when working in private, I try to behave like I am still working in public.  It is a good practice to make sure everyone knows what they are doing is publicly visible and having some discussion about what is appropriate is a good idea.

**Comment by shamindras** [comment]
@jarrodmillman - thanks. As discussed, if you could please just send me a list of all of the github usernames of our entire project team - I can create the gitter chatroom.

Feel free to paste the names in a reply comment here.

Thanks

**Comment by jarrodmillman** [comment]
Everyone should be listed here:
https://github.com/orgs/berkeley-stat222/teams/capstone2016

**Comment by shamindras** [comment]
Thanks @jarrodmillman . I've set this up but had a few issues with permissions. I spoke to GH staff and they mentioned that we need to do the following:

> @shamindras You probably need to allow 3rd party access to your org: https://gitter.zendesk.com/hc/en-us/articles/202460552-Why-isn-t-my-GitHub-organisation-appearing-

and **more specifically** the following:

> The repo, mousestyles, is under an org called berkeley-stat222. Visit https://github.com/organizations/berkeley-stat222/settings/applications and allow Gitter public access. You can add the webhook manually and use the Cutom integration: https://github.com/organizations/EricTroupeTester-Org/settings/hooks

I don't have access to the `stat-222` organisation. Could you please update this?

**Comment by jarrodmillman** [comment]
@shamindras : Do I still need to do anything? Or is this resolved?

**Comment by shamindras** [comment]
@jarrodmillman - I believe we need to add 3rd party permissions for `mousetstyles` based on the links provided in my previous post. I can't seem to access the `berkeley-stat222` organisation.

Currently we can all chat but there is a nice feature where you can see all of the latest branches and commits on the right hand side of gitter screen which doesn't appear atm.

If you are really busy we could do this last step on Monday.

**Comment by dylandaniels** [comment]
Close this out @shamindras ?

**Comment by shamindras** [comment]
@dylandaniels - there is technically one set of permissions that needs to be changed to wrap this up. But `gitter` is usable so happy to close it and make the final change next week with Jarrod.
