### ISSUE TITLE
Set up infrastructure

### ISSUE THREAD

**Issue by peterasujan** [berkeley-stat222/mousestyles#4]
#### Infrastructure pieces needed:
- [ ] Linting (how about [this](https://pylint.org) @jarrodmillman ?)
- [ ] ***CONTRIBUTOR.md***
  - This may need to point to more detailed files in doc/dev/
  - Style guide
- [ ] Travis CI
- [ ] Coverage
- [ ] Sphinx

#### Python
- [ ] Data loader

#### Assorted todo's
- [x] Close fake issues #1 and #2

**Comment by shamindras** [comment]
Issues #1 and #2 are now fixed.

**Comment by jcpalumbo3** [comment]
THIS IS NOT REAL
