### ISSUE TITLE
Move *FLOW.md files to a sub-directory of `doc`

### ISSUE THREAD

**Issue by peterasujan** [berkeley-stat222/mousestyles#40]
The top-level folder is getting cluttered. Also, this will allow us to eventually have sphinx render these into html/pdf/etc.

**Comment by jarrodmillman** [comment]
I would create `doc/dev` to move developer documentation into.  This will make it easier to organize things when we set up Sphinx.

**Comment by peterasujan** [comment]
Resolved in #59.
