### ISSUE TITLE
Add tools/README.md and document pre-commit hook

### ISSUE THREAD

**Issue by peterasujan** [berkeley-stat222/mousestyles#46]

**Comment by jarrodmillman** [comment]
This is just an FYI.

It looks like you committed your `pre-commit` hook with the execution bit already set.

```
$ ls -l tools/pre-commit
-rwxrwxr-x. 1 jarrod jarrod 287 Apr  6 11:57 tools/pre-commit
```

This is probably why @dylandaniels didn't need to set the execute bit to get it to work for him when he just copied it to `.git/hooks`.

**Comment by peterasujan** [comment]
Ah, that makes sense, thanks!

**Comment by dylandaniels** [comment]
@peterasujan is this done?

**Comment by peterasujan** [comment]
In progress. I'm doing this along with https://github.com/berkeley-stat222/mousestyles/issues/14#issuecomment-207855457.
