### ISSUE TITLE
Set up Infrastructure

### ISSUE THREAD

**Issue by lynnzhao92** [berkeley-stat222/mousestyles#5]
## First Week Infrastructure Set up
- [ ] Create CONTRIBUTOR.md and include: (doc/develop/..)
     - how to make pull request
     - how to make issues, report bugs
     - dependencies (should specify in setup.py / requirements.txt)
- [ ] Understand and create a recipe of pull request work flow
- [ ] Data Loader
    - actually try all the loading, use *mousestyles/mousestyles/data/__init__.py*
    - Consult HTM_begin_script: check [this](https://www.msri.org/people/members/chillar/files/BY), change codes to functions
- [ ] Create the Checklist Documentation to tell what code should have
      - Tests, Docstrings, Style Guides (package pep8 automatically check style errors), verb named function, Python2/3 Compatibility, Auto Check Doc. Standard are followed
- [ ] Clean the repository to have separate Data, Analysis and Plot files 
- [ ] Travis CI / Coverage, setup.py (Week 2)
      - set the license, description, etc. variables in setup.py
      -  CI / Coverage: quick fix, talk to jarrod @jarrodmillman 
          - http://docs.astropy.org/en/stable/development/testguide.html
          - http://pytest.org/latest/goodpractices.html#goodpractices
          - "goodpractices" says "avoid `__init__.py` files in your test directories.", but astropy is doing just that
          - "goodpractices" continues "With inlined tests you might put `__init__.py` into test directories and make them installable as part of your application."
          - I think I would just add the `__init__.py` to the tests directories.
          - you may also need to add the `*npy` files using `package_data` see
              - https://github.com/statlab/permute/blob/master/setup.py
- [ ] Sphinx (Week2)
      - See https://github.com/statlab/permute for examples

**Comment by alannaiverson** [comment]
Good start on a CONTRIBUTOR.md file [here](https://github.com/statlab/permute/blob/master/CONTRIBUTE.rst)!

**Comment by peterasujan** [comment]
Closing in favor of separate issues. See [infrastructure tag](https://github.com/berkeley-stat222/mousestyles/labels/infrastructure).
