### ISSUE TITLE
Fill out package information in setup.py

### ISSUE THREAD

**Issue by peterasujan** [berkeley-stat222/mousestyles#56]
- [x] license
- [x] description
- [x] other things?

See https://pythonhosted.org/an_example_pypi_project/setuptools.html#setting-up-setup-py

**Comment by jarrodmillman** [comment]
This isn't super pressing and I have a couple of ideas I want to think about before finalizing this.  I should be able to revisit this next week.

**Comment by dylandaniels** [comment]
@shamindras is this done?

**Comment by shamindras** [comment]
@dylandaniels - this is with @jarrodmillman per his comment above.

I have formally assigned back to him for his review.
