### ISSUE TITLE
Review of  TESTFLOW

### ISSUE THREAD

**Issue by boyinggong** [berkeley-stat222/mousestyles#64]
- [x] The link to `test_data_utils.py` on that page just goes the main repo
- [x] Remove old examples for numpy tests
- [x] Add instruction for the make test
- [x] Since we are using pytest for our testing framework rather than numpy tests. All documents about testing should be changed to pytest.
- [x] Add pytest examples rather than the numpy examples. We are using pytest

**Comment by boyinggong** [comment]
@jarrodmillman @dylandaniels @peterasujan @shamindras We're going to refine the testing part. Is there any concerns or suggestions for the testing? Thanks.

**Comment by shamindras** [comment]
@boyinggong - as per the gitter discussion it may be helpful to change **all** of the `numpy` examples to `pytest`

**Comment by jarrodmillman** [comment]
I wouldn't spend too much time adding examples to the documentation.  It will be much more useful to add examples to the code.
