### ISSUE TITLE
Add git lg command to GITFLOW

### ISSUE THREAD

**Issue by peterasujan** [berkeley-stat222/mousestyles#73]
See: https://github.com/peterasujan/dotfiles/blob/master/gitconfig#L5
(this is just one example)

**Comment by shamindras** [comment]
@peterasujan - I can add this in however do you mean CONTRIBUTING.rst?

In this case - could we close this issue and merge this task into #74?

**Comment by peterasujan** [comment]
Yes, I forgot we didn't have a separate file for that. However, I'm not sure this is important enough to exist in the main CONTRIBUTING file. It might make sense to create a new file with more advanced git tips and other non-essential information.
