### ISSUE TITLE
Add code review guidelines somewhere (CONTRIBUTING.rst?)

### ISSUE THREAD

**Issue by peterasujan** [berkeley-stat222/mousestyles#74]
This is a really nice set of guidelines for code review:
https://github.com/thoughtbot/guides/tree/master/code-review

**Comment by shamindras** [comment]
@peterasujan - I can add these into CONTRIBUTING.rst

Is there anything else to put in there i.e. we can make it a larger commit.

**Comment by peterasujan** [comment]
Maybe just do a pass over the the whole file for clarity and see if anything else is missing?
I agree that this could be done at the same time as #73.
