### ISSUE TITLE
Clean strain_classification.py

### ISSUE THREAD

**Issue by hduongtrong** [berkeley-stat222/mousestyles#75]
We want to clean up strain_classification.py file provided to us by the researchers. We should have functions to 

1. [ ] load_data function that return the X, y array
2. [ ] report_accuracy function that run a model and report performance

**Comment by doutib** [comment]
@jarrodmillman can we have one python script to load the data and another python script to perform classification? Or are we constrained to have only one script for the whole project?

**Comment by dylandaniels** [comment]
@doutib No--there's no limit on number of scripts. You should divide the code between files so that they create logical partitions of functionality.
