### ISSUE TITLE
Need to make a variable glossary

### ISSUE THREAD

**Issue by pigriver123** [berkeley-stat222/mousestyles#83]

**Comment by jcpalumbo3** [comment]
Refer to the glossary started in the [Overview](https://github.com/berkeley-stat222/mousestyles/blob/master/doc/problem/overview.md) section.

**Comment by jarrodmillman** [comment]
It also may make sense to create an index.  That way anyone who is interested in when we use the word in the report can find a link or page number.  It think this should be easy to do in Sphinx and will look into it.

**Comment by HongfeiZhao** [comment]
@jarrodmillman , I am working on adding variable description. Do you know the meaning of M_AS files under intervals file? I think it may refers to the start and end point of movement in AS. Also, do you know the meaning of C_idx_HB files under txy_coords files.

**Comment by dylandaniels** [comment]
@HongfeiZhao I'm still unsure what M_AS means. It's one of the questions I was going to ask the Tecott Lab group tomorrow. 

As for C_idx_HB--that's a boolean variable that indicates whether the mouse was in the home base or not. To see how all the files in that folder interact, it's helpful to look at/play around with the mousestyles.data.load_intervals() function:

https://github.com/berkeley-stat222/mousestyles/blob/master/mousestyles/data/__init__.py

**Comment by HongfeiZhao** [comment]
Thanks, @dylandaniels , it's helpful!

**Comment by dylandaniels** [comment]
@HongfeiZhao what's the status on this?

**Comment by HongfeiZhao** [comment]
I am not sure what variables should I add? It seems there are explanation for 'AS' and 'IS'. Should I give a description for all the data variables like M_AS, C_idx_HB? @dylandaniels

**Comment by HongfeiZhao** [comment]
Please close the issue, it has been addressed @pigriver123
