### ISSUE TITLE
Include all requirements

### ISSUE THREAD

**Issue by doutib** [berkeley-stat222/mousestyles#97]
@jarrodmillman

**Comment by shamindras** [comment]
@doutib - what is required here? Is there anything I can assist with?

**Comment by doutib** [comment]
Yes it is related to this file, basically add missing libraries (e.g. Scikit learn)

**Comment by shamindras** [comment]
@doutib - I see. Please create a new branch > then new PR to update the requirements for the specific version of sckit learn you require.

Once the PR is created just tag @jarrodmillman know and he can review/ MRG it.

If you have already created the PR, just tag @jarrodmillman in it for review

**Comment by dylandaniels** [comment]
@shamindras @doutib what is this issue about?

**Comment by doutib** [comment]
@dylandaniels This is about making sure that all the requirements are fulfilled. Even though I think everything is in the requirement.txt file now, I think we should keep the issue until the end of the project since the content of the file depends on the code we will write until then.

**Comment by shamindras** [comment]
@doutib - If your requirements are now included let's close this specific issue.

We can re-open a new issue (with a new associated PR) if there are additional requirements to include.
