### ISSUE TITLE
Convert hcm_data_begin script to use new data loaders

### ISSUE THREAD

**Issue by dylandaniels** [berkeley-stat222/mousestyles#98]
The file needs to be modified to use the new data format.

**Comment by jarrodmillman** [comment]
@dylandaniels It looks like no one is using this file.  Is it OK to delete the file and close this?

**Comment by dylandaniels** [comment]
Yeah, I'll take care of that now!

**Comment by dylandaniels** [comment]
@jarrodmillman Nevermind, looks like you already deleted it here: 7e6e555ede6
